### ISSUE TITLE
I got an error.

### ISSUE THREAD

**Issue by RaphaelBunck** [Ulterius/client#55]
Hello,
I opened the Ulterius client on chrome, and got the following error:
`Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://192.168.178.31:22006" from accessing a cross-origin frame.
    at contents (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5154)
    at Function.map (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14862)
    at ot.fn.init.ot.fn.(anonymous function) [as contents] (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5271)
    at HTMLIFrameElement.eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1894)
    at Function.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14059)
    at ot.fn.init.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:11922)
    at e.bindActivityDetectors (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1853)
    at e.init (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/ActivityMonitorController.js:1:255)
    at onLoaded (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/content.js:1:979)
    at eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/ComponentFactory.js:1:943)`

I also get no icons and get a 404 in the console when it tries to load them. 

`Failed to load resource: the server responded with a status of 404 (Not Found)   logo.png`

**Comment by Codeusa** [comment]
Seems like your browser addon StayFocused is conflicting with the client.

**Comment by RaphaelBunck** [comment]
Wow u responded within a minute :D 
Will delete the plugin, I never use it anyways haha.

**Comment by RaphaelBunck** [comment]
I have no error now, but still no icons.

**Comment by RaphaelBunck** [comment]
Nevermind, I seem to have lost my ability to read. Thank you very much!
